/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jaso83934

import java.time.DayOfWeek
import java.time.LocalDate
import java.time.temporal.TemporalAdjusters

fun main() {
    val base = LocalDate.of(2021, 12, 3)
    val date = base.with(TemporalAdjusters.dayOfWeekInMonth(2, DayOfWeek.WEDNESDAY))
    println(date) // 2021-12-08
}
