/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jaso92559.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
