@startuml
autonumber
ユーザエージェント -> クライアント:  /secure/endpoint\nへアクセス
activate クライアント
クライアント -> クライアント: 認可済みチェック -> NG
クライアント --> ユーザエージェント: 認可のためのリダイレクト指示
deactivate クライアント

ユーザエージェント -> 認可サーバ: 認可リクエスト
activate 認可サーバ
認可サーバ -> 認可サーバ: (認証及び)認可
認可サーバ -> クライアント: 認可コード通知
activate クライアント
クライアント --> 認可サーバ: ack
deactivate クライアント
認可サーバ --> ユーザエージェント: 元々のリクエスト\n/secure/endpoint\nへリダイレクト指示？
deactivate 認可サーバ

クライアント -> 認可サーバ: /code with 認可コード
activate クライアント
activate 認可サーバ
認可サーバ --> クライアント: アクセストークン
deactivate 認可サーバ
deactivate クライアント

ユーザエージェント -> クライアント: /secure/endpoint
activate クライアント
クライアント -> リソースサーバ: リソース要求 with アクセストークン
activate リソースサーバ
リソースサーバ --> クライアント: リソース
deactivate リソースサーバ
クライアント --> ユーザエージェント: 応答
deactivate クライアント

@enduml
