DROP TABLE IF EXISTS EMPLOYEE;  
CREATE TABLE EMPLOYEE (  
email VARCHAR(50) NOT NULL  PRIMARY KEY,  
password VARCHAR(50) NOT NULL,  
firstName VARCHAR(50) NOT NULL, 
lastName VARCHAR(50) NOT NULL,
role VARCHAR(50) NOT NULL
);  